# Generated by Django 4.2.3 on 2024-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lot', models.DecimalField(decimal_places=3, max_digits=3)),
                ('profit_or_loss', models.DecimalField(decimal_places=3, max_digits=15)),
                ('time_on_chart', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('risk', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
            ],
        ),
    ]
