# Generated by Django 4.2.3 on 2024-05-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_trade_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='lot',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_or_loss',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
