# Generated by Django 4.2.3 on 2024-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_trade_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
