# Generated by Django 4.2.3 on 2024-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_trade_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time_on_chart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
