# Generated by Django 4.2.3 on 2024-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_alter_trade_time_on_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='risk',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
    ]
