# Generated by Django 4.2.3 on 2024-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_trade_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(blank=True, default='Gold', max_length=20, null=True),
        ),
    ]
